baseURL = 'https://timhuang.co/'
languageCode = 'en-us'
title = 'Tim Huang'
theme = 'paper'

[menus]
  [[menus.main]]
    name = 'Projects'
    pageref = '/projects'
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.googleAnalytics]
    id = 'G-J3B99K797L'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'timhuangg'               # twitter.com/timhuangg
  github = 'timothy-huang'                 # github.com/timothy-huang
  linkedin = 'timhuangg'             # linkedin.com/in/timhuangg

  # home page profile
  name = 'Tim Huang'
  bio = 'Writing, building, and learning. Left big tech to learn more about life. Currently migrating old posts from timhuang.beehiiv.com.'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false             # disable post navigation
  monoDarkIcon = false                      # show monochrome dark mode icon
  math = false                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon